# Generated by Django 5.2.16 on 2026-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, unique=True)),
                ('position_options', models.JSONField(blank=True, default=list, help_text='e.g. ["approve", "reject", "uncertain"]')),
                ('decision_options', models.JSONField(blank=True, default=list, help_text='e.g. ["approve", "deny"], or [] for research_debate')),
                ('research_guardrail_prompt', models.TextField(blank=True, help_text="Appended to the research Activity's system prompt for this case type (decision 14).")),
            ],
        ),
    ]
