# Generated by Django 5.2.16 on 2026-08-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_casetypeconfig_default_consultant_persona_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casetypeconfig',
            old_name='research_guardrail_prompt',
            new_name='policy_context',
        ),
        migrations.AlterField(
            model_name='casetypeconfig',
            name='policy_context',
            field=models.TextField(blank=True, help_text="Domain grounding text fed into the consultant and, once a debate starts, every participant's argument prompt and the judge's verdict prompt (ADR 0010) — e.g. lending norms for loan_approval. Renamed from the unused research_guardrail_prompt, which was never wired to any code path."),
        ),
        migrations.AddField(
            model_name='casetypeconfig',
            name='required_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of {name, type, description} the consultant must collect before finalizing (ADR 0010) — enforced via a dynamically-built structured-output schema, not just prompt wording. Empty list (e.g. research_debate) keeps the intake fully free-form, unchanged from before this field existed.'),
        ),
    ]
