# Generated by Django 5.2.16 on 2026-07-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved')], default='OPEN', max_length=20)),
                ('finalized_payload', models.JSONField(blank=True, help_text="Set only once the user approves; becomes the Case's content.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('consultant_persona', models.ForeignKey(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.PROTECT, to='debates.agentpersona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.PositiveIntegerField()),
                ('speaker', models.CharField(choices=[('user', 'User'), ('consultant', 'Consultant')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='consultations.consultationsession')),
            ],
            options={
                'ordering': ['turn_number'],
                'unique_together': {('session', 'turn_number')},
            },
        ),
    ]
