# Generated by Django 5.2.16 on 2026-09-09 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CofounderGeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(help_text='Base64-encoded image bytes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='cofounder_chat.cofoundersession')),
            ],
        ),
    ]
