# Generated by Django 5.2.16 on 2026-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofounder_chat', '0002_cofoundergeneratedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofounderturn',
            name='step',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
