# Generated by Django 5.2.16 on 2026-07-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationsession',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], default='OPEN', max_length=20),
        ),
    ]
