# Generated by Django 5.2.16 on 2026-07-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('debates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('final_decision', models.CharField(blank=True, help_text='Button-selected from CaseTypeConfig.decision_options, never typed; null when that list is empty (research_debate).', max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='human_review', to='debates.debate')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
