# Generated by Django 5.2.16 on 2026-07-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('consultant', 'Consultant'), ('judge', 'Judge')], max_length=20)),
                ('role_description', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('model_config', models.JSONField(help_text='Which LLM, temperature, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_strategy', models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel'), ('judge_directed', 'Judge-directed')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ARGUING', 'Arguing'), ('CONVERGING', 'Converging'), ('JUDGED', 'Judged'), ('NO_CONSENSUS', 'No consensus'), ('FAILED', 'Failed')], default='OPEN', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('max_rounds', models.PositiveIntegerField()),
                ('convergence_config', models.JSONField(blank=True, default=dict)),
                ('opening_statement', models.TextField(blank=True, null=True)),
                ('closing_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='cases.case')),
                ('judge_persona', models.ForeignKey(limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.PROTECT, related_name='judged_debates', to='debates.agentpersona')),
            ],
        ),
        migrations.CreateModel(
            name='ConvergenceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('method', models.CharField(default='structured_signals', help_text='Single accurate label for the check actually implemented.', max_length=50)),
                ('signals', models.JSONField(help_text='position_stable, confidence_spread, uncited_changes, etc.')),
                ('result', models.BooleanField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convergence_checks', to='debates.debate')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('source_url', models.TextField(blank=True, null=True)),
                ('source_title', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debates.agentpersona')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_findings', to='debates.debate')),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debates.agentpersona')),
                ('responds_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='debates.argument')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='debates.debate')),
                ('cites_research_finding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='debates.researchfinding')),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cited_arguments', models.ManyToManyField(related_name='cited_in_verdicts', to='debates.argument')),
                ('debate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verdict', to='debates.debate')),
            ],
        ),
        migrations.CreateModel(
            name='DebateParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stance_seed', models.TextField(blank=True, null=True)),
                ('persona_snapshot', models.JSONField(help_text="Frozen copy of the persona's config at the moment the debate started.")),
                ('agent_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='debates.agentpersona')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='debates.debate')),
            ],
            options={
                'unique_together': {('debate', 'agent_persona')},
            },
        ),
    ]
