# Generated by Django 5.2.16 on 2026-07-18 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='consultation_session',
            field=models.OneToOneField(blank=True, help_text='Traceability back to the consultation that produced this case (decision 10).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_case', to='consultations.consultationsession'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
