# Generated by Django 5.2.16 on 2026-07-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casetypeconfig',
            name='position_options',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["reject", "uncertain", "approve"]. List ORDER matters (spec 0008): it doubles as the divergence→convergence spectrum the debate-thread visualization plots arguments along — seed it most-divergent-first, most-convergent-last, not just as an unordered set of valid values.'),
        ),
    ]
