# Generated by Django 5.2.16 on 2026-07-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_casetypeconfig_position_options'),
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetypeconfig',
            name='default_consultant_persona',
            field=models.ForeignKey(default=12, help_text="Required — every case type must have a consultant configured (decision 10: the consultant runs for every case, every time). No default/null: a case type missing this simply can't be saved (spec 0009).", limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='debates.agentpersona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetypeconfig',
            name='default_judge_persona',
            field=models.ForeignKey(default=1, help_text='Required — same fail-fast reasoning as default_consultant_persona (spec 0009).', limit_choices_to={'role': 'judge'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='debates.agentpersona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casetypeconfig',
            name='default_max_rounds',
            field=models.PositiveIntegerField(default=3, help_text="Behavioral default for an auto-created Debate's max_rounds (spec 0009)."),
        ),
        migrations.AddField(
            model_name='casetypeconfig',
            name='default_participant_personas',
            field=models.ManyToManyField(blank=True, help_text='Frozen into DebateParticipant.persona_snapshot when a consultation is approved (spec 0009). Not enforced non-empty at the DB level — the approval activity checks and fails loudly instead of silently creating a zero-participant Debate.', limit_choices_to={'role': 'participant'}, related_name='+', to='debates.agentpersona'),
        ),
    ]
